jwt:
  secret: njxgfNABEZr5BrU29vFmjfHXemZngUXZVxWOZ/N00PE=
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventos
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update # Crea y elimina las tablas en cada reinicio
    show-sql: true # Muestra las consultas SQL en la consola

# Configuración para H2
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console