jwt:
  secret: njxgfNABEZr5BrU29vFmjfHXemZngUXZVxWOZ/N00PE=
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eventos
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update