#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/eventos
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # Cambia a 'update' en producción
    show-sql: true # Muestra las consultas SQL en la consola
  h2:
    console:
      enabled: true # Habilita la consola de H2
      path: /h2-console